version: 2

node_container: &node_container
  docker:
    - image: circleci/node:10.13.0-stretch
  working-directory: ~/workspace/code

jobs:
  build:
    <<: *node_container
    steps:
      - checkout
      - run:
          name: Build Depedencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
      - persist_to_workspace:
          root: ~/workspace
          paths:
            - code
  test:
    <<: *node_container
    steps:
      - attach_workspace:
          at: ~/workspace
      - run:
          name: Test Unit
          command: yarn test:unit

workflows:
  version: 2
  build-test:
    jobs:
      - build
      - test:
          requires:
            - build
