version: 2

defaults: &defaults
  docker:
    - image: circleci/node:10.13.0-stretch
  working-directory: ~/playground

jobs:
  build:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: Build Depedencies
          command: yarn install
      - run:
          name: Build
          command: yarn build
  test:
    <<: *defaults
    steps:
      - run:
          name: Test Unit
          command: yarn test:unit
